onboarding = false

[ui]
agent_panel_sort = "priority"
sidebar_collapsed_mode = "hidden"
[ui.toast]
delivery = "system"

[experimental]
switch_ascii_input_source_in_prefix = true

[theme]
name = "terminal"
auto_switch = false

[[keys.command]]
key = "prefix+e"
type = "popup"
command = "nvim ."
description = "open nvim"
width = "80%"
height = "80%"
