# tmuxのプリフィックスキー
# 例: Ctrl+a に変更する場合
set -g prefix C-x
unbind C-b
bind C-x send-prefix


# ウィンドウ内のペイン移動を hjkl で行う
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# アクティブペインの枠線の色（非アクティブは暗く）
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour39   # 明るい水色

# ペイン番号の表示時間
set -g display-panes-time 2000

#マウス操作を有効にする
set -g mouse on
