# Prefix(Ctrl-b)をCtrl-jに変更する
unbind-key C-b
set-option -g prefix C-j

# Alt-h,j,k,l で左,下,上,右ペインに移動
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

# アクティブペインの枠線の色（非アクティブは暗く）
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour39   # 明るい水色

# ペイン番号の表示時間
set -g display-panes-time 2000

# マウスホイールでヒストリではなくスクロールできるようにする
set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

